# Generated by Django 3.2.4 on 2021-07-08 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='featured_song', to='musics.song')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrys_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
