# Generated by Django 3.2.4 on 2021-06-29 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO entry_entry (
            id,
            title,
            content,
            date,
            song_id,
            writer_id
        )
        SELECT
            id,
            title,
            content,
            date,
            song_id,
            writer_id
        FROM
            mlog_entry;
        """,reverse_sql="""
        INSERT INTO mlog_entry (
            id,
            title,
            content,
            date,
            song_id,
            writer_id
        )
        SELECT
            id,
            title,
            content,
            date,
            song_id,
            writer_id
        FROM
            entry_entry;
        """)
    ]
