# Generated by Django 3.2.4 on 2021-09-03 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0017_song_artwork_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0004_auto_20210903_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='featured_song', to='musics.song', verbose_name='song'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=30, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrys_writer', to=settings.AUTH_USER_MODEL, verbose_name='writer'),
        ),
    ]
