# Generated by Django 3.2.4 on 2021-08-27 01:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='images/defaults/accounts/profile/default.jpg', upload_to=accounts.models.User.get_image_path),
        ),
    ]
