# Generated by Django 3.2.4 on 2021-08-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(max_length=20, verbose_name='handle name'),
        ),
    ]
