# Generated by Django 3.2.4 on 2021-06-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biograph',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
