# Generated by Django 3.2.4 on 2021-08-31 23:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biograph',
            field=models.TextField(blank=True, max_length=200, verbose_name='biograph'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='images/defaults/accounts/profile/default.jpg', upload_to=accounts.models.User.get_image_path, verbose_name='profile image'),
        ),
    ]
