# Generated by Django 3.2.4 on 2021-06-23 01:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='accounts/images/profile/default/default.jpg', upload_to=accounts.models.User.get_image_path),
        ),
    ]
