# Generated by Django 3.2.4 on 2021-06-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
