version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/base:2021.07

    steps:
      - run: set -x
      - setup_remote_docker
      - checkout
      - run:
          name: Make Directory for result
          command: mkdir mlog_project/result/
      - run:
          name: Set environment variables
          command: |
              echo $MLOG_OAUTH_GOOGLE_CLIENT_ID
              echo $MLOG_OAUTH_GOOGLE_KEY
              echo $MLOG_OAUTH_GOOGLE_SECRET
              echo $MLOG_SECRET_KEY
      - run:
          name: Copy app source to app container
          command: |
              docker-compose -f docker/docker-compose.yml -f docker/docker-compose.test.yml up --no-start app
              docker cp . docker_app_1:.
      - run: 
          name: Test
          command: docker-compose -f docker/docker-compose.yml -f docker/docker-compose.test.yml run --name app_test app bash -c "sleep 60 && python mlog_project/manage.py test --noinput mlog_project/"
#      - run:
#          name: Copy test results from container
#          command: |
#              docker cp app_test:/mlog_project/result/unittest.xml mlog_project/result/
#      - run: ls -la mlog_project/result
#      - store_test_results:
#          path: mlog_project/result
      - run: 
          name: Down containers
          command: docker-compose -f docker/docker-compose.yml -f docker/docker-compose.test.yml down