version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
      - image: circleci/redis
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: mlog_db
          MYSQL_USER: mlog_db_user
          MYSQL_PASSWORD: password

    steps:
      - checkout
      - run: mkdir mysql sql