version: 2.1
jobs:
  build:
    machine: 
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run: set -x
      - run: mkdir mysql sql
      - run: echo $MLOG_OAUTH_GOOGLE_CLIENT_ID
      - run: echo $MLOG_OAUTH_GOOGLE_KEY
      - run: echo $MLOG_OAUTH_GOOGLE_SECRET
      - run: echo $MLOG_SECRET_KEY
      - run: docker-compose -f docker/docker-compose.test.yml up