version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.07

    steps:
      - checkout
      - run: set -x
      - run: mkdir mysql sql
      - run: echo $MLOG_OAUTH_GOOGLE_CLIENT_ID
      - run: echo $MLOG_OAUTH_GOOGLE_KEY
      - run: echo $MLOG_OAUTH_GOOGLE_SECRET
      - run: echo $MLOG_SECRET_KEY