version: '3'

services:
    app:
        ports: 
            - 8000:8000
        environment: 
            - DJANGO_DATABASE=docker
            - SELECT2_DEFAULT=select2_docker
            - CELERY_BROKER_DEFAULT=docker
            - CELERY_RESULT_BACKENDS_DEFAULT=docker
        env_file: 
            - ./python/app_envfile.env
        command: bash -c "cd ./mlog_project && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"