version: '3'

services:
    db:
        image: mysql:5.7
        ports: 
            - 33060:3306
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ../mysql:/var/lib/mysql
            - ../sql:/docker-entrypoint-initdb.d

    redis:
        image: redis:6.2


    celery:
        build: 
            context: ..
            dockerfile: ./docker/python/Dockerfile
        environment: 
            - DJANGO_DATABASE=docker
            - CELERY_BROKER_DEFAULT=docker
            - CELERY_RESULT_BACKENDS_DEFAULT=docker
        env_file: 
            - ./python/app_envfile.env
        volumes: 
            - ../mlog_project:/mlog_project
        command: bash -c "apt update -y && apt install -y python-celery && cd /mlog_project && celery -A mlog_project worker >/dev/null"
        depends_on: 
            - redis
    

    app:
        build: 
            context: ..
            dockerfile: ./docker/python/Dockerfile
        volumes:
            - ../mlog_project:/mlog_project
        environment: 
            - DJANGO_DATABASE=docker
            - SELECT2_DEFAULT=select2_docker
            - CELERY_BROKER_DEFAULT=docker
            - CELERY_RESULT_BACKENDS_DEFAULT=docker
        env_file: 
            - ./python/app_envfile.env
        depends_on: 
            - db
            - redis
            - celery

