version: '3'

services:
    db:
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mlog_db
            MYSQL_USER: mlog_db_user
            MYSQL_PASSWORD: password
        volumes:
            - ../mysql:/var/lib/mysql
            - ../sql:/docker-entrypoint-initdb.d

            
    nginx:
        image: nginx:1.20
        ports: 
            - 8000:8000
        volumes: 
            - ../nginx/conf:/etc/nginx/conf.d
            - ../nginx/uwsgi_params:/etc/nginx/uwsgi_params
        depends_on: 
            - app

    celery:
        image: ${IMAGE_URI}:${IMAGE_TAG}

    app:
        image: ${IMAGE_URI}:${IMAGE_TAG}
        env_file: 
            - ./python/app_envfile.env
        command: bash -c "cd ./mlog_project && python manage.py migrate && uwsgi --socket :8001 --module mlog_project.wsgi --py-autoreload 1"
        expose:
            - 8001