version: '3'

services:
    nginx:
        image: nginx:1.20
        ports: 
            - 8000:8000
        volumes: 
            - ../nginx/conf:/etc/nginx/conf.d
            - ../nginx/uwsgi_params:/etc/nginx/uwsgi_params
        depends_on: 
            - python


    db:
        image: mysql:5.7
        ports: 
            - 33060:3306
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mlog_db
            MYSQL_USER: mlog_db_user
            MYSQL_PASSWORD: password
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ../mysql:/var/lib/mysql
            - ../sql:/docker-entrypoint-initdb.d

    cache:
        image: redis:6.2

    python:
        image: python:3.8
        volumes:
            - ../mlog_project:/mlog_project
        environment: 
            -  DJANGO_DATABASE=docker
        command: bash -c "cd ./mlog_project && pip install -r requirements.txt && python manage.py migrate && uwsgi --socket :8001 --module mlog_project.wsgi --py-autoreload 1"
        expose:
            - 8001
        depends_on: 
            - db
            - cache