version: '3'

services:
    db:
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mlog_db
            MYSQL_USER: mlog_db_user
            MYSQL_PASSWORD: password
        volumes:
            - ../mysql:/var/lib/mysql
            - ../sql:/docker-entrypoint-initdb.d

    app:
        ports: 
            - 8000:8000
        environment: 
            - MLOG_USE_S3=True
            - DJANGO_DATABASE=docker
            - SELECT2_DEFAULT=select2_docker
            - CELERY_BROKER_DEFAULT=docker
            - CELERY_RESULT_BACKENDS_DEFAULT=docker
        env_file: 
            - ./python/app_envfile.env
        command: bash -c "cd ./mlog_project && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"