version: '3'

services:
    nginx:
        image: nginx:1.20
        ports: 
            - 8000:8000
        volumes: 
            - ../nginx/conf:/etc/nginx/conf.d
            - ../nginx/uwsgi_params:/etc/nginx/uwsgi_params
            - ../mlog_project/static:/static
            - ../mlog_project/media:/media
        depends_on: 
            - app


    app:
        env_file: 
            - ./python/app_envfile.env
        environment:
            - MLOG_IS_DEVELOP=False
        command: bash -c "cd ./mlog_project && python manage.py migrate && uwsgi --socket :8001 --module mlog_project.wsgi --py-autoreload 1"
        expose:
            - 8001