version: '3'

services:
    redis:
        image: redis:6.2

            
    nginx:
        image: ${NGINX_IMAGE_URI}:${NGINX_IMAGE_TAG}
        build:
            context: ..
            dockerfile: ./docker/nginx/Dockerfile.production
        ports: 
            - 8000:8000
        depends_on: 
            - app

    celery:
        image: ${PYTHON_IMAGE_URI}:${PYTHON_IMAGE_TAG}
        build: 
            context: ..
            dockerfile: ./docker/python/Dockerfile.production
        env_file: 
            - ./python/app_envfile.env
        environment: 
            - CELERY_BROKER_DEFAULT=docker
            - CELERY_RESULT_BACKENDS_DEFAULT=docker
        command: bash -c "apt install -y python-celery && cd /usr/src/app && celery -A mlog_project worker >/dev/null"
        depends_on: 
            - redis

    app:
        image: ${PYTHON_IMAGE_URI}:${PYTHON_IMAGE_TAG}
        build: 
            context: ..
            dockerfile: ./docker/python/Dockerfile.production
        env_file: 
            - ./python/app_envfile.env
        #command: bash -c "cd /usr/src/app && python manage.py collectstatic --noinput && python manage.py migrate && uwsgi --socket :8001 --module mlog_project.wsgi --py-autoreload 1"
        command: bash -c "cd /usr/src/app && python manage.py migrate && uwsgi --socket :8001 --module mlog_project.wsgi --py-autoreload 1"
        ports:
            - 8001:8001
        depends_on: 
            - redis
            - celery
        environment:
            - MLOG_DEBUG_STATE=False
            - SELECT2_DEFAULT=select2_docker
            - CELERY_BROKER_DEFAULT=docker
            - CELERY_RESULT_BACKENDS_DEFAULT=docker