# Generated by Django 3.2.4 on 2021-06-28 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0002_songcheckedactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailCheckedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logined_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
