# Generated by Django 3.2.4 on 2021-07-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='spotify_link',
            field=models.URLField(blank=True),
        ),
    ]
