# Generated by Django 3.2.4 on 2021-06-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO musics_genre (
            id,
            genre_name
        )
        SELECT
            id,
            genre_name
        FROM
            mlog_genre;
        """,reverse_sql="""
        INSERT INTO mlog_genre (
            id,
            genre_name
        )
        SELECT
            id,
            genre_name
        FROM
            musics_genre;
        """)
    ]
