# Generated by Django 3.2.4 on 2021-06-29 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_auto_20210629_0904'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO musics_artist (
            id,
            artist_name,
            artist_biograph,
            artist_name_id
        )
        SELECT
            id,
            artist_name,
            artist_biograph,
            artist_name_id
        FROM 
            mlog_artist;
        """,reverse_sql="""
        INSERT INTO mlog_artist (
            id,
            artist_name,
            artist_biograph,
            artist_name_id
        )
        SELECT
            id,
            artist_name,
            artist_biograph,
            artist_name_id
        FROM
            musics_artist;
        """)
    ]
