# Generated by Django 3.2.4 on 2021-07-09 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_artist_belong_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='musics.song'),
        ),
    ]
