# Generated by Django 3.2.4 on 2021-06-29 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_auto_20210629_0921'),
    ]

    operations = [
    ]
