# Generated by Django 3.2.4 on 2021-07-26 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_auto_20210726_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='belong_to',
        ),
        migrations.AddField(
            model_name='artist',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='musics.artist'),
        ),
    ]
