# Generated by Django 3.2.4 on 2021-06-29 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_auto_20210629_0930'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO musics_artist_genre (
            id,
            artist_id,
            genre_id
        )
        SELECT
            id,
            artist_id,
            genre_id
        FROM
            mlog_artist_genre
        """,reverse_sql="""
        INSERT INTO mlog_artist_genre (
            id,
            artist_id,
            genre_id
        )
        SELECT
            id,
            artist_id,
            genre_id
        FROM
            musics_artist_genre
        """)
    ]
