# Generated by Django 3.2.4 on 2021-06-29 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_auto_20210629_0944'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO musics_song_artist (
            id,
            song_id,
            artist_id
        )
        SELECT
            id,
            song_id,
            artist_id
        FROM
            mlog_song_artist;
        """,reverse_sql="""
        INSERT INTO mlog_song_artist (
            id,
            song_id,
            artist_id
        )
        SELECT
            id,
            song_id,
            artist_id
        FROM
            musics_song_artist;
        """)
    ]
