# Generated by Django 3.2.4 on 2021-06-29 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0006_auto_20210629_0948'),
    ]

    operations = [
    ]
