# Generated by Django 3.2.4 on 2021-07-27 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0006_auto_20210727_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='BelongTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_artist', to='musics.artist')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_artist', to='musics.artist')),
            ],
        ),
    ]
