# Generated by Django 3.2.4 on 2021-07-27 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0007_belongto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='belong_to',
        ),
    ]
