# Generated by Django 3.2.4 on 2021-07-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0008_remove_artist_belong_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BelongTo',
        ),
    ]
