# Generated by Django 3.2.4 on 2021-08-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0010_artist_belong_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
