# Generated by Django 3.2.4 on 2021-08-03 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0011_artist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='slug',
        ),
    ]
