# Generated by Django 3.2.4 on 2021-09-21 00:23

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0017_song_artwork_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='song',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
    ]
