# Generated by Django 3.2.4 on 2021-09-03 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musics', '0017_song_artwork_url'),
        ('favorite_artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.artist', verbose_name='artist'),
        ),
        migrations.AlterField(
            model_name='favoriteartist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
