# Generated by Django 3.2.4 on 2021-08-28 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0002_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactThreads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MLG', 'このサービスについて'), ('ACC', 'アカウントについて'), ('ART', 'アーティストについて'), ('SON', '曲について'), ('USR', 'ユーザについて'), ('ENT', 'エントリについて')], max_length=3)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='reply',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.AddField(
            model_name='contactcontent',
            name='parent_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contactthreads'),
        ),
        migrations.AddField(
            model_name='contactcontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
