# Generated by Django 3.2.4 on 2021-09-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210828_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactcontent',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='contactthreads',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
