# Generated by Django 3.2.4 on 2021-09-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20210902_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcontent',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
