# Generated by Django 3.2.4 on 2021-09-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20210902_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcontent',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
