# Generated by Django 3.2.4 on 2021-09-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contactcontent_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactthreads',
            name='category',
            field=models.CharField(choices=[('MLG', 'このサービスについて'), ('ACC', 'アカウントについて'), ('ART', 'アーティストについて'), ('SON', '曲について'), ('USR', 'ユーザについて'), ('ENT', 'エントリについて')], max_length=3, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='contactthreads',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='created at'),
        ),
    ]
