# Generated by Django 3.2.4 on 2021-09-03 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0007_auto_20210903_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcontent',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='created_at',
            field=models.DateTimeField(editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='parent_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contactthreads', verbose_name='parent thread'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='updated_at',
            field=models.DateTimeField(verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='contactthreads',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
