# Generated by Django 3.2.4 on 2021-06-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlog', '0002_auto_20210614_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='subgenre',
            field=models.ManyToManyField(blank=True, to='mlog.SubGenre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='subgenre',
            field=models.ManyToManyField(blank=True, to='mlog.SubGenre'),
        ),
    ]
