# Generated by Django 3.2.4 on 2021-06-24 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlog', '0007_auto_20210624_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readhistory',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlog.entry'),
        ),
        migrations.AlterField(
            model_name='readhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
