# Generated by Django 3.2.4 on 2021-06-28 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlog', '0011_favoriteartist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='subgenre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='subgenre',
        ),
        migrations.DeleteModel(
            name='SubGenre',
        ),
    ]
