# Generated by Django 3.2.4 on 2021-06-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlog', '0012_auto_20210628_0945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
