# Generated by Django 3.2.4 on 2021-06-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlog', '0013_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
