# Generated by Django 3.2.4 on 2021-06-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlog', '0014_delete_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteArtist',
        ),
    ]
