# Generated by Django 3.2.4 on 2021-06-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlog', '0015_delete_favoriteartist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readhistory',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='readhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArtistCheckedHistory',
        ),
        migrations.DeleteModel(
            name='ReadHistory',
        ),
    ]
